from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from field import mod_inverse

@dataclass(frozen=True)
class Point:
    x: Optional[int]
    y: Optional[int]

    @property
    def is_infinity(self) -> bool:
        return self.x is None and self.y is None

    def __repr__(self) -> str:
        if self.is_infinity:
            return "Point(∞)"
        return f"Point({self.x}, {self.y})"


# Singleton for the identity element
INFINITY = Point(None, None)


@dataclass(frozen=True)
class EllipticCurve:
    Attributes: # type:ignore
        # a, b: Curve coefficients
        # p: The prime modulus (defines the finite field)
        # G: Generator point (base point)
        # n: Order of the generator point (number of points in the subgroup generated by G)
    a: int
    b: int
    p: int
    G: Point
    n: int

    def is_valid(self) -> bool:
        discriminant = (4 * pow(self.a, 3, self.p) + 27 * pow(self.b, 2, self.p)) % self.p
        return discriminant != 0

    def is_on_curve(self, point: Point) -> bool:
        # Verify that a point satisfies the curve equation.
        # Defines an elliptic curve y^2 = x^3 + ax + b over GF(p).

        if point.is_infinity:
            return True
        lhs = pow(point.y, 2, self.p) # type: ignore
        rhs = (pow(point.x, 3, self.p) + self.a * point.x + self.b) % self.p # type: ignore
        return lhs == rhs


    def point_add(self, P: Point, Q: Point) -> Point:
        # Add two distinct points P and Q on the curve.

        # Returns the point R = P + Q.

        # Algorithm:
            # 1. If either point is ∞, return the other (identity property).
            # 2. If P.x == Q.x and P.y != Q.y, they are inverses → return ∞.
            # 3. If P == Q, delegate to point_double.
            # 4. Otherwise, compute slope λ = (Q.y - P.y) / (Q.x - P.x) mod p
               # then:
                   # R.x = λ^2 - P.x - Q.x (mod p)
                   # R.y = λ(P.x - R.x) - P. (mod p)

        if P.is_infinity:
            return Q
        if Q.is_infinity:
            return P
        if P.x == Q.x and P.y != Q.y:
            return INIFNITY # type: ignore
        if P == Q:
            return self.point_double(P)
        lam = ((Q.y - P.y) * mod_inverse(Q.x - P.x, self.p)) % self.p # type: ignore
        rx = (lam * lam - P.x - Q.x) % self.p # type: ignore
        ry = (lam * (P.x - rx) - P.y) % self.p # type: ignore
        return Point(rx,ry)

    def point_double(self, P: Point) -> Point:
        if P.is_infinity:
            return INFINITY # type: ignore
        if P.y == 0:
            return INFINITY # type: ignore
        lam = ((3 * P.x * P.x + self.a) * mod_inverse(2 * P.y, self.p)) % self.p # type:ignore
        rx = (lam * lam - 2 * P.x) % self.p # type:ignore 
        ry = (lam * (P.x - rx) - P.y) % self.p # type:ignore
        return Point(rx,ry) 

    def point_negate(self, P: Point) -> Point:
        if P.is_infinity:
            return INFINITY
        return Point(P.x, (-P.y) % self.p) # type:ignore

    def scalar_multiply(self, k: int, P: Point) -> Point: # type:ignore
       # REPLACE THIS WITH MONTGOMERY LADDER SOON
        result = INFINITY
        for bit in bin(k)[2:]:
            result = self.point_double(result)
            if bit == '1':
                result = self.point_add(result, P)
            return result
