"""
ECC Jargon Glossary
====================

GCD (Greatest Common Divisor):
    The largest integer that divides both a and b with no remainder.
    gcd(12, 8) = 4. In ECC, we need gcd(a, p) == 1 to guarantee that
    a has a modular inverse. Since p is prime, every a in [1, p-1]
    satisfies this automatically.

GF(p) (Galois Field of order p):
    The set of integers {0, 1, 2, ..., p-1} where all arithmetic wraps
    around mod p. It's a "field" because addition, subtraction,
    multiplication, and division all work (except dividing by 0).
    Think of it like clock arithmetic, but the clock has p hours.

Modular Inverse (a^-1 mod p):
    The number x such that a * x ≡ 1 (mod p). It's "division" in
    modular arithmetic. You can't do fractions mod p, so instead of
    computing (b / a) mod p, you compute b * (a^-1) mod p.

pow(a, e, p):
    Python built-in. Computes a^e mod p efficiently using fast
    modular exponentiation (square-and-multiply internally). It does
    NOT compute a^e first and then reduce — it reduces at every step,
    so it works fine even for 256-bit numbers.

Order (of a point G):
    The smallest positive integer n such that n * G = ∞ (the identity).
    After n additions of G to itself, you wrap back to the start.
    This n defines the size of the subgroup generated by G and is
    critical for key generation: your private key must be in [1, n-1].

Generator Point (G):
    A specific point on the curve chosen so that repeatedly adding it
    to itself generates a large subgroup of points. All public keys
    are multiples of G. The choice of G is part of the curve spec
    (e.g., secp256k1 defines a specific G).

Scalar:
    Just a plain integer (as opposed to a point). Your private key is
    a scalar. "Scalar multiplication" means multiplying a point by an
    integer (adding the point to itself that many times).

ECDLP (Elliptic Curve Discrete Logarithm Problem):
    Given Q = k * G, find k. This is the hard problem that makes ECC
    secure. You can compute Q from k easily (scalar multiplication is
    fast), but recovering k from Q is computationally infeasible for
    large curves.

Discriminant (4a^3 + 27b^2):
    A value derived from the curve coefficients. If it's zero mod p,
    the curve has a singularity (a cusp or self-intersection), which
    breaks the group structure. We check it's nonzero to confirm the
    curve is "smooth" and safe to use.

QR (Quadratic Residue):
    A number a is a QR mod p if there exists some x where x^2 ≡ a (mod p).
    Not every number has a square root in modular arithmetic — roughly
    half do, half don't. This matters when recovering y from an
    x-coordinate on the curve.

r and s (in ECDSA context):
    r = the x-coordinate of a random curve point (k * G), reduced mod n.
       It binds the signature to a specific random point on the curve.
    s = encodes the actual proof that you know the private key.
       It combines the message hash, r, and private key, all wrapped
       in the random k so the private key isn't exposed.
    Together (r, s) form the signature. Neither alone is sufficient.

r and s (in Extended Euclidean Algorithm context):
    r = the "remainder" being tracked. Starts as (a, p) and converges
       toward the GCD via repeated division.
    s = the "coefficient" — tracks what multiplier of the original `a`
       produces the current remainder. When r reaches the GCD (1),
       s holds the modular inverse.
"""
