"""
Pygame visualizer for elliptic curve points.

Displays a window with a button to generate points on a curve.
Plots the generator point and subsequent multiples, showing coordinates.
Uses the TOY_CURVE from params.py for manageable size.
"""

import sys
import math
import pygame

from curve import EllipticCurve, Point, INFINITY
from field import t_s
from params import TOY_CURVE

# Window dimensions
WIDTH, HEIGHT = 800, 600
BACKGROUND_COLOR = (30, 30, 30)
POINT_COLOR = (100, 200, 255)
TEXT_COLOR = (255, 255, 255)
CURVE_DOT_COLOR = (80, 80, 80)
BUTTON_COLOR = (50, 150, 50)
BUTTON_HOVER_COLOR = (70, 180, 70)
BUTTON_RECT = pygame.Rect(20, 20, 200, 50)

# Maximum number of points to display (to avoid infinite loops)
MAX_POINTS = 30


def generate_points(curve: EllipticCurve) -> list[Point]:
    """Return a list of points generated by repeatedly adding G to itself."""
    points: list[Point] = []
    for i in range(1, curve.n):
        pt = curve.scalar_multiply(i, curve.G)
        if pt.is_infinity:
            break
        points.append(pt)
        if len(points) >= MAX_POINTS:
            break
    return points


def scale_points(
    points: list[Point], width: int, height: int, margin: int = 60
) -> list[tuple[int, int]]:
    """Map point coordinates to pixel positions, preserving aspect ratio."""
    if not points:
        return []

    xs = [p.x for p in points if p.x is not None]
    ys = [p.y for p in points if p.y is not None]

    if not xs or not ys:
        return []

    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)

    # Avoid division by zero if all points have same coordinate
    if max_x == min_x:
        max_x = min_x + 1
    if max_y == min_y:
        max_y = min_y + 1

    # Compute scale factors
    range_x = max_x - min_x
    range_y = max_y - min_y

    # Available drawing area
    draw_width = width - 2 * margin
    draw_height = height - 2 * margin

    # Use the larger range to preserve aspect ratio
    scale = min(draw_width / range_x, draw_height / range_y)

    # Center the points
    center_x = (min_x + max_x) / 2
    center_y = (min_y + max_y) / 2

    pixel_points = []
    for pt in points:
        if pt.x is None or pt.y is None:
            continue
        px = int((pt.x - center_x) * scale + width / 2)
        py = int((pt.y - center_y) * scale + height / 2)
        pixel_points.append((px, py))
    return pixel_points


def draw_button(screen: pygame.Surface, mouse_pos: tuple[int, int]) -> bool:
    """Draw the generate button and return True if it is being hovered."""
    hovered = BUTTON_RECT.collidepoint(mouse_pos)
    color = BUTTON_HOVER_COLOR if hovered else BUTTON_COLOR
    pygame.draw.rect(screen, color, BUTTON_RECT)
    font = pygame.font.SysFont(None, 30)
    text = font.render("Generate Curve", True, TEXT_COLOR)
    text_rect = text.get_rect(center=BUTTON_RECT.center)
    screen.blit(text, text_rect)
    return hovered


def draw_points(
    screen: pygame.Surface,
    points: list[Point],
    pixel_points: list[tuple[int, int]],
) -> None:
    """Draw each point as a circle and its coordinates as text."""
    font = pygame.font.SysFont(None, 20)
    for pt, (px, py) in zip(points, pixel_points):
        # Draw point
        pygame.draw.circle(screen, POINT_COLOR, (px, py), 5)
        # Draw coordinates
        coord_text = f"({pt.x}, {pt.y})"
        text_surf = font.render(coord_text, True, TEXT_COLOR)
        text_rect = text_surf.get_rect(topleft=(px + 10, py - 10))
        screen.blit(text_surf, text_rect)


def get_all_curve_points(curve: EllipticCurve) -> list[Point]:
    """Return a list of all points on the curve (excluding infinity)."""
    points: list[Point] = []
    for x in range(curve.p):
        y2 = (pow(x, 3, curve.p) + curve.a * x + curve.b) % curve.p
        if pow(y2, (curve.p - 1) // 2, curve.p) == 1:
            y = t_s(y2, curve.p)
            points.append(Point(x, y))
            if y != 0:
                points.append(Point(x, (-y) % curve.p))
    return points


def draw_curve_dots(
    screen: pygame.Surface,
    pixel_points: list[tuple[int, int]],
) -> None:
    """Draw small dots for all curve points."""
    for px, py in pixel_points:
        pygame.draw.circle(screen, CURVE_DOT_COLOR, (px, py), 2)


def main() -> None:
    pygame.init()
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    pygame.display.set_caption("ECC Visualizer")
    clock = pygame.time.Clock()

    points: list[Point] = []
    pixel_points: list[tuple[int, int]] = []
    all_points: list[Point] = []
    pixel_points_curve: list[tuple[int, int]] = []

    running = True
    while running:
        mouse_pos = pygame.mouse.get_pos()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.MOUSEBUTTONDOWN:
                if BUTTON_RECT.collidepoint(event.pos):
                    # Generate points using the toy curve
                    points = generate_points(TOY_CURVE)
                    pixel_points = scale_points(points, WIDTH, HEIGHT)
                    all_points = get_all_curve_points(TOY_CURVE)
                    pixel_points_curve = scale_points(all_points, WIDTH, HEIGHT)

        screen.fill(BACKGROUND_COLOR)
        draw_button(screen, mouse_pos)
        if all_points and pixel_points_curve:
            draw_curve_dots(screen, pixel_points_curve)
        if points and pixel_points:
            draw_points(screen, points, pixel_points)

        pygame.display.flip()
        clock.tick(60)

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()
